"""
Slater-type orbital overlap integrals for NDDO methods.

Exact port of PYSEQM's diatom_overlap_matrix_PM6_SP:
  - SET function with z1=zeta_A, z2=zeta_B convention
  - S111, S211, S121, S221, S222 local-frame overlaps
  - Quaternion rotation to molecular frame (rotate_with_quaternion)
  - Assembly: di[p,s]=S211*c0, di[s,p]=-S121*c0,
              di[p,p]=-S221*r0⊗r0 + S222*(r1⊗r1+r2⊗r2)

Reference: diat_overlap_PM6_SP.py in PYSEQM (2025 update).
"""
from __future__ import annotations

import numpy as np
from .params import ElementParams, ANG_TO_BOHR, principal_qn
from .rotation import _rotation_matrix


def _aintgs(alpha: float, n_max: int = 7) -> np.ndarray:
    """A-integrals: a_k(alpha) = exp(-alpha)/alpha * recurrence.

    a_1 = exp(-alpha)/alpha
    a_k = a_1 + (k-1)*a_{k-1}/alpha

    Matches PYSEQM aintgs() exactly. Default n_max=7 covers jcall up to 6
    (S-S overlap needs A[6]). For qn=4..6 atoms (Br, I) bump n_max to 13.
    """
    if abs(alpha) < 1e-10:
        return np.zeros(n_max)

    a = np.zeros(n_max)
    a[0] = np.exp(-alpha) / alpha
    for k in range(1, n_max):
        a[k] = a[0] + k * a[k - 1] / alpha
    return a


def _bintgs(beta: float, n_max: int = 7) -> np.ndarray:
    """B-integrals: b_k(beta).

    b_1 = 2*sinh(beta)/beta  (even function)
    b_k recurrence with alternating signs.

    Three regimes matching PYSEQM PM6_SP:
      |beta| <= 1e-6:  b(0) limit values
      1e-6 < |beta| <= 0.5:  Taylor series (x^2, x^4, x^6 terms)
      |beta| > 0.5:  exact recurrence
    """
    b = np.zeros(n_max)
    x = beta

    if abs(x) <= 1e-6:
        # Exact at beta=0 — even indices are 2/(k+1), odd are 0
        for k in range(n_max):
            if k % 2 == 0:
                b[k] = 2.0 / (k + 1)
            else:
                b[k] = 0.0
        return b

    if abs(x) <= 0.5:
        # Taylor series expansion (PYSEQM diat_overlapD lines 5337-5344)
        # Even-indexed b's: b_k(x) = sum_{m=0,2,4,6} x^m * 2/(m!*(m+k))
        # Odd-indexed b's:  b_k(x) = sum_{m=1,3,5} -x^m * 2/(m!*(m+k))
        x2 = x * x
        x3 = x * x2
        x4 = x2 * x2
        x5 = x2 * x3
        x6 = x2 * x4
        # Generated by the closed-form pattern up to b[12]:
        even_coeffs = [
            (2.0, 1/3, 1/60, 1/2520),       # b[0]: (i=0) 2/(m!*(m+1))
            (2/3, 1/5, 1/84, 1/3240),        # b[2]: (i=2) 2/(m!*(m+3))
            (2/5, 1/7, 1/108, 1/3960),       # b[4]: (i=4) 2/(m!*(m+5))
            (2/7, 1/9, 1/132, 1/4680),       # b[6]: (i=6) 2/(m!*(m+7))
            (2/9, 1/11, 1/156, 1/5400),      # b[8]: (i=8) 2/(m!*(m+9))
            (2/11, 1/13, 1/180, 1/6120),     # b[10]: 2/(m!*(m+11))
            (2/13, 1/15, 1/204, 1/6840),     # b[12]: 2/(m!*(m+13))
        ]
        odd_factors = [
            (-2/3, -1/15, -1/420),           # b[1]: x, x^3, x^5
            (-2/5, -1/21, -1/540),           # b[3]
            (-2/7, -1/27, -1/660),           # b[5]
            (-2/9, -1/33, -1/780),           # b[7]
            (-2/11, -1/39, -1/900),          # b[9]
            (-2/13, -1/45, -1/1020),         # b[11]
        ]
        for k in range(n_max):
            if k % 2 == 0:
                c = even_coeffs[k // 2]
                b[k] = c[0] + c[1] * x2 + c[2] * x4 + c[3] * x6
            else:
                c = odd_factors[k // 2]
                b[k] = c[0] * x + c[1] * x3 + c[2] * x5
        return b

    # Exact recurrence for |beta| > 0.5  (b_{k+1} = ±tx + tmx + k*b_k/x)
    x_clamped = np.clip(x, -500.0, 500.0)
    tx = np.exp(x_clamped) / x
    tmx = -np.exp(-x_clamped) / x
    sign = 1.0  # b[0] = +tx + tmx; b[1] uses -tx + tmx; alternates
    b[0] = tx + tmx
    for k in range(1, n_max):
        sign = -sign  # b[1]: sign=-1, b[2]: sign=+1, ...
        b[k] = sign * tx + tmx + k * b[k - 1] / x
    return b


def _pyseqm_sp_overlap_matrix(
    pA: ElementParams,
    pB: ElementParams,
    coordA: np.ndarray,
    coordB: np.ndarray,
) -> np.ndarray | None:
    """Fallback overlap for high-principal-quantum-number sp atoms.

    The native formulas below cover H through third-row sp pairs. Br/I and
    heavier PM6 parameter-table atoms need the general spheroidal PYSEQM port
    that is already vendored for the d-orbital path.
    """

    from ._pyseqm_port.constants_np import qnD_int, qn_int
    from ._pyseqm_port.diat_overlapD_np import diatom_overlap_matrixD

    R_vec = coordB - coordA
    R_ang = float(np.linalg.norm(R_vec))
    if R_ang < 1e-10:
        return None

    swap = pA.Z < pB.Z
    if swap:
        p1, p2, c1, c2 = pB, pA, coordB, coordA
    else:
        p1, p2, c1, c2 = pA, pB, coordA, coordB

    R12 = c2 - c1
    R12_ang = float(np.linalg.norm(R12))
    xij = np.asarray([R12 / R12_ang], dtype=np.float64)
    R_bohr = np.asarray([R12_ang * ANG_TO_BOHR], dtype=np.float64)
    ni = np.asarray([int(p1.Z)], dtype=np.int64)
    nj = np.asarray([int(p2.Z)], dtype=np.int64)
    zeta_i = np.asarray([[p1.zeta_s, p1.zeta_p, getattr(p1, "zeta_d", 0.0)]], dtype=np.float64)
    zeta_j = np.asarray([[p2.zeta_s, p2.zeta_p, getattr(p2, "zeta_d", 0.0)]], dtype=np.float64)

    try:
        full = diatom_overlap_matrixD(ni, nj, xij, R_bohr, zeta_i, zeta_j, qn_int, qnD_int)[0]
    except Exception:
        return None

    overlap = full[: p1.n_basis, : p2.n_basis].copy()
    return overlap.T if swap else overlap


def overlap_molecular_frame(
    pA: ElementParams, pB: ElementParams,
    coordA: np.ndarray, coordB: np.ndarray,
) -> np.ndarray:
    """Compute overlap matrix in the molecular frame.

    Exact port of PYSEQM diatom_overlap_matrix_PM6_SP.

    Args:
        pA, pB: element parameters for atoms A and B
        coordA, coordB: coordinates in Angstrom

    Returns:
        di: (nA, nB) overlap matrix in molecular frame
            Indices: 0=s, 1=px, 2=py, 3=pz
    """
    R_vec = coordB - coordA
    R = np.linalg.norm(R_vec)
    nA = pA.n_basis
    nB = pB.n_basis

    if R < 1e-10:
        S = np.zeros((nA, nB))
        for k in range(min(nA, nB)):
            S[k, k] = 1.0
        return S

    R_bohr = R * ANG_TO_BOHR

    # Principal quantum numbers (row of periodic table)
    qnA = principal_qn(pA.Z)
    qnB = principal_qn(pB.Z)

    # PYSEQM convention: heavier atom first (qnA >= qnB)
    # If lighter atom is first, swap and transpose
    if qnA < qnB:
        di_swap = overlap_molecular_frame(pB, pA, coordB, coordA)
        return di_swap.T

    # Determine jcall (PYSEQM convention)
    if qnA == 1 and qnB == 1:
        jcall = 2
    elif qnA == 2 and qnB == 1:
        jcall = 3
    elif qnA == 2 and qnB == 2:
        jcall = 4
    elif qnA == 3 and qnB == 1:
        jcall = 431
    elif qnA == 3 and qnB == 2:
        jcall = 5
    elif qnA == 3 and qnB == 3:
        jcall = 6
    else:
        fallback = _pyseqm_sp_overlap_matrix(pA, pB, coordA, coordB)
        if fallback is not None:
            return fallback
        raise ValueError(f"Unsupported pair: qn=({qnA},{qnB})")

    # ================================================================
    # SET function: z1 = zeta_A, z2 = zeta_B  (PYSEQM convention)
    # alpha = 0.5 * R * (z1 + z2)
    # beta  = 0.5 * R * (z1 - z2)
    # ================================================================

    # A111, B111: s_A - s_B
    alpha_ss = 0.5 * R_bohr * (pA.zeta_s + pB.zeta_s)
    beta_ss = 0.5 * R_bohr * (pA.zeta_s - pB.zeta_s)
    A111 = _aintgs(alpha_ss)
    B111 = _bintgs(beta_ss)

    # A211, B211: p_A - s_B  (z1 = zA_p, z2 = zB_s)
    if nA > 1:
        alpha_ps = 0.5 * R_bohr * (pA.zeta_p + pB.zeta_s)
        beta_ps = 0.5 * R_bohr * (pA.zeta_p - pB.zeta_s)
        A211 = _aintgs(alpha_ps)
        B211 = _bintgs(beta_ps)
    else:
        A211 = np.zeros(5)
        B211 = np.zeros(5)

    # A121, B121: s_A - p_B  (z1 = zA_s, z2 = zB_p)
    if nB > 1:
        alpha_sp = 0.5 * R_bohr * (pA.zeta_s + pB.zeta_p)
        beta_sp = 0.5 * R_bohr * (pA.zeta_s - pB.zeta_p)
        A121 = _aintgs(alpha_sp)
        B121 = _bintgs(beta_sp)
    else:
        A121 = np.zeros(5)
        B121 = np.zeros(5)

    # A22, B22: p_A - p_B  (z1 = zA_p, z2 = zB_p)
    if nA > 1 and nB > 1:
        alpha_pp = 0.5 * R_bohr * (pA.zeta_p + pB.zeta_p)
        beta_pp = 0.5 * R_bohr * (pA.zeta_p - pB.zeta_p)
        A22 = _aintgs(alpha_pp)
        B22 = _bintgs(beta_pp)
    else:
        A22 = np.zeros(5)
        B22 = np.zeros(5)

    # ================================================================
    # Local-frame overlaps (exact PYSEQM PM6_SP formulas)
    # ================================================================
    S111 = 0.0
    S211 = 0.0
    S121 = 0.0
    S221 = 0.0
    S222 = 0.0

    if jcall == 2:
        # (1s|1s) — PYSEQM jcall==2
        S111 = ((pA.zeta_s * pB.zeta_s * R_bohr ** 2) ** 1.5
                * (A111[2] * B111[0] - B111[2] * A111[0])
                / 4.0)

    elif jcall == 3:
        # (2s_A|1s_B) — PYSEQM jcall==3
        S111 = (pB.zeta_s ** 1.5 * pA.zeta_s ** 2.5 * R_bohr ** 4
                * (A111[3] * B111[0] - B111[3] * A111[0]
                   + A111[2] * B111[1] - B111[2] * A111[1])
                / (np.sqrt(3.0) * 8.0))

        # (2pσ_A|1s_B) — PYSEQM S211 jcall==3
        if nA > 1:
            S211 = (pB.zeta_s ** 1.5 * pA.zeta_p ** 2.5 * R_bohr ** 4
                    * (A211[2] * B211[0] - B211[2] * A211[0]
                       + A211[3] * B211[1] - B211[3] * A211[1])
                    / 8.0)

    elif jcall == 4:
        # (2s|2s) — PYSEQM jcall==4
        S111 = ((pA.zeta_s * pB.zeta_s) ** 2.5 * R_bohr ** 5
                * (A111[4] * B111[0] + B111[4] * A111[0]
                   - 2.0 * A111[2] * B111[2])
                / 48.0)

        if nA > 1 and nB > 1:
            # (2pσ_A|2s_B) = S211 — PYSEQM jcall==4
            S211 = ((pB.zeta_s * pA.zeta_p) ** 2.5 * R_bohr ** 5
                    * (A211[3] * (B211[0] - B211[2])
                       - A211[1] * (B211[2] - B211[4])
                       + B211[3] * (A211[0] - A211[2])
                       - B211[1] * (A211[2] - A211[4]))
                    / (16.0 * np.sqrt(3.0)))

            # (2s_A|2pσ_B) = S121 — PYSEQM jcall==4
            # NOTE: B-terms have OPPOSITE sign from S211 (PYSEQM convention)
            S121 = ((pB.zeta_p * pA.zeta_s) ** 2.5 * R_bohr ** 5
                    * (A121[3] * (B121[0] - B121[2])
                       - A121[1] * (B121[2] - B121[4])
                       - B121[3] * (A121[0] - A121[2])
                       + B121[1] * (A121[2] - A121[4]))
                    / (16.0 * np.sqrt(3.0)))

            # (2pσ|2pσ) = S221 — PYSEQM jcall==4
            # NOTE: This is NOT the same as our old S_local[1,1]!
            w = (pB.zeta_p * pA.zeta_p) ** 2.5 * R_bohr ** 5 / 16.0
            S221 = -w * (B22[2] * (A22[4] + A22[0])
                         - A22[2] * (B22[4] + B22[0]))

            # (2pπ|2pπ) = S222 — PYSEQM jcall==4
            S222 = (0.5 * w
                    * (A22[4] * (B22[0] - B22[2])
                       - B22[4] * (A22[0] - A22[2])
                       - A22[2] * B22[0]
                       + B22[2] * A22[0]))

    elif jcall == 431:
        # (3s_A|1s_B) — PYSEQM jcall==431 (heavy qn=3 + H)
        S111 = (pB.zeta_s ** 1.5 * pA.zeta_s ** 3.5 * R_bohr ** 5
                * (A111[4] * B111[0]
                   + 2.0 * B111[1] * A111[3]
                   - 2.0 * A111[1] * B111[3]
                   - B111[4] * A111[0])
                / (np.sqrt(10.0) * 24.0))

        # (3pσ_A|1s_B) — PYSEQM S211 jcall==431
        if nA > 1:
            S211 = (pB.zeta_s ** 1.5 * pA.zeta_p ** 3.5 * R_bohr ** 5
                    * (A211[3] * (B211[0] + B211[2])
                       - A211[1] * (B211[4] + B211[2])
                       + B211[1] * (A211[2] + A211[4])
                       - B211[3] * (A211[2] + A211[0]))
                    / (8.0 * np.sqrt(30.0)))

    elif jcall == 5:
        # (3s|2s) — PYSEQM jcall==5
        S111 = (pB.zeta_s ** 2.5 * pA.zeta_s ** 3.5 * R_bohr ** 6
                * (A111[5] * B111[0]
                   + B111[1] * A111[4]
                   - 2.0 * B111[2] * A111[3]
                   - 2.0 * A111[2] * B111[3]
                   + B111[4] * A111[1]
                   + B111[5] * A111[0])
                / (np.sqrt(30.0) * 48.0))

        if nA > 1 and nB > 1:
            # (3pσ_A|2s_B) = S211 — PYSEQM jcall==5
            S211 = (pB.zeta_s ** 2.5 * pA.zeta_p ** 3.5 * R_bohr ** 6
                    * (A211[4] * B211[0]
                       + B211[1] * A211[5]
                       - 2.0 * B211[3] * A211[3]
                       - 2.0 * A211[2] * B211[2]
                       + A211[1] * B211[5]
                       + A211[0] * B211[4])
                    / (48.0 * np.sqrt(10.0)))

            # (3s_A|2pσ_B) = S121 — PYSEQM jcall==5
            S121 = (pB.zeta_p ** 2.5 * pA.zeta_s ** 3.5 * R_bohr ** 6
                    * ((A121[4] * B121[0] - A121[5] * B121[1])
                       + 2.0 * (A121[3] * B121[1] - A121[4] * B121[2])
                       - 2.0 * (A121[1] * B121[3] - A121[2] * B121[4])
                       - (A121[0] * B121[4] - A121[1] * B121[5]))
                    / (48.0 * np.sqrt(10.0)))

            # (3pσ|2pσ) = S221 — PYSEQM jcall==5
            S221 = (pB.zeta_p ** 2.5 * pA.zeta_p ** 3.5 * R_bohr ** 6
                    * ((A22[3] * B22[0] - A22[5] * B22[2])
                       + (A22[2] * B22[1] - A22[4] * B22[3])
                       - (A22[1] * B22[2] - A22[3] * B22[4])
                       - (A22[0] * B22[3] - A22[2] * B22[5]))
                    / (16.0 * np.sqrt(30.0)))

            # (3pπ|2pπ) = S222 — PYSEQM jcall==5
            S222 = (pB.zeta_p ** 2.5 * pA.zeta_p ** 3.5 * R_bohr ** 6
                    * ((A22[5] - A22[3]) * (B22[0] - B22[2])
                       + (A22[4] - A22[2]) * (B22[1] - B22[3])
                       - (A22[3] - A22[1]) * (B22[2] - B22[4])
                       - (A22[2] - A22[0]) * (B22[3] - B22[5]))
                    / (32.0 * np.sqrt(30.0)))

    elif jcall == 6:
        # (3s|3s) — PYSEQM jcall==6
        S111 = ((pA.zeta_s * pB.zeta_s) ** 3.5 * R_bohr ** 7
                * (A111[6] * B111[0]
                   - 3.0 * B111[2] * A111[4]
                   + 3.0 * A111[2] * B111[4]
                   - A111[0] * B111[6])
                / 1440.0)

        if nA > 1 and nB > 1:
            # (3pσ_A|3s_B) = S211 — PYSEQM jcall==6
            S211 = ((pB.zeta_s * pA.zeta_p) ** 3.5 * R_bohr ** 7
                    * ((A211[5] * B211[0] + A211[6] * B211[1])
                       + (-A211[4] * B211[1] - A211[5] * B211[2])
                       - 2.0 * (A211[3] * B211[2] + A211[4] * B211[3])
                       - 2.0 * (-A211[2] * B211[3] - A211[3] * B211[4])
                       + (A211[1] * B211[4] + A211[2] * B211[5])
                       + (-A211[0] * B211[5] - A211[1] * B211[6]))
                    / (480.0 * np.sqrt(3.0)))

            # (3s_A|3pσ_B) = S121 — PYSEQM jcall==6
            S121 = ((pB.zeta_p * pA.zeta_s) ** 3.5 * R_bohr ** 7
                    * ((A121[5] * B121[0] - A121[6] * B121[1])
                       + (A121[4] * B121[1] - A121[5] * B121[2])
                       - 2.0 * (A121[3] * B121[2] - A121[4] * B121[3])
                       - 2.0 * (A121[2] * B121[3] - A121[3] * B121[4])
                       + (A121[1] * B121[4] - A121[2] * B121[5])
                       + (A121[0] * B121[5] - A121[1] * B121[6]))
                    / (480.0 * np.sqrt(3.0)))

            # (3pσ|3pσ) = S221 — PYSEQM jcall==6
            S221 = ((pB.zeta_p * pA.zeta_p) ** 3.5 * R_bohr ** 7
                    * ((A22[4] * B22[0] - A22[6] * B22[2])
                       - 2.0 * (A22[2] * B22[2] - A22[4] * B22[4])
                       + (A22[0] * B22[4] - A22[2] * B22[6]))
                    / 480.0)

            # (3pπ|3pπ) = S222 — PYSEQM jcall==6
            S222 = ((pB.zeta_p * pA.zeta_p) ** 3.5 * R_bohr ** 7
                    * ((A22[6] - A22[4]) * (B22[0] - B22[2])
                       - 2.0 * (A22[4] - A22[2]) * (B22[2] - B22[4])
                       + (A22[2] - A22[0]) * (B22[4] - B22[6]))
                    / 960.0)

    # ================================================================
    # Rotation to molecular frame (exact PYSEQM PM6_SP assembly)
    # ================================================================

    # Unit vector from A to B (positive direction, PYSEQM xij convention)
    v = R_vec / R

    # Rotation matrix: rotate v to x-axis
    # Same quaternion as PYSEQM's rotate_with_quaternion
    rot = _rotation_matrix(v)

    # PYSEQM: rot = rot.transpose(1,2), then c0 = rot[:,:,0]
    # c0 = column 0 of transposed rot = row 0 of original rot
    r0 = rot[0]  # sigma direction (along bond)
    r1 = rot[1]  # pi_x direction
    r2 = rot[2]  # pi_y direction

    # Assemble di (overlap in molecular frame)
    di = np.zeros((nA, nB))

    # s-s: always present
    di[0, 0] = S111

    if jcall == 3 or jcall == 431:
        # Heavy-H: di[p_A, s_B] = S211 * c0
        if nA > 1:
            for k in range(3):
                di[k + 1, 0] = S211 * r0[k]

    elif jcall == 4 or jcall == 5 or jcall == 6:
        if nA > 1 and nB > 1:
            # p_A - s_B: di[p, s] = S211 * c0
            for k in range(3):
                di[k + 1, 0] = S211 * r0[k]

            # s_A - p_B: di[s, p] = -S121 * c0  (PYSEQM minus sign!)
            for k in range(3):
                di[0, k + 1] = -S121 * r0[k]

            # p_A - p_B: di[p,p] = -S221*r0⊗r0 + S222*(r1⊗r1 + r2⊗r2)
            # PYSEQM: M = [-S221, S222, S222]
            #          B = rot_T * M
            #          di[1:,1:] = B @ rot
            for k in range(3):
                for l in range(3):
                    di[k + 1, l + 1] = (
                        -S221 * r0[k] * r0[l]
                        + S222 * (r1[k] * r1[l] + r2[k] * r2[l])
                    )

    return di
