"""openCHEESE: open 3D shape/electrostatic similarity and embeddings.

This package is the standalone public namespace for the CHEESE-like work. In
this repository the implementation currently delegates to the MLX backend in
``mlxmolkit``. New user code should import from ``opencheese`` so the project
can be split into an independent package without another API rename.
"""

from opencheese.descriptors import (
    CheeseAlignmentConfig,
    CheeseAlignmentResult,
    CheeseBatch,
    CheeseSimilarityResult,
    align_cheese_pair,
    atom_gaussian_parameters_mlx,
    cheese_alignment_matrix,
    cheese_batch,
    cheese_batch_from_rdkit_mols,
    cheese_similarity_matrix_mlx,
    cheese_similarity_pairs_mlx,
    electrostatic_carbo_matrix_mlx,
    electrostatic_overlap_matrix_mlx,
    electrostatic_paired_overlap_mlx,
    electrostatic_potential_on_grid_metal,
    electrostatic_potential_on_grid_mlx,
    electrostatic_self_overlap_mlx,
    electrostatic_similarity_matrix_mlx,
    electrostatic_similarity_to_template_grids_mlx,
    electrostatic_similarity_to_template_grids_tiled_mlx,
    gaussian_shape_overlap_matrix_mlx,
    gaussian_shape_paired_overlap_mlx,
    gaussian_shape_self_overlap_mlx,
    horn_align_pairwise_mlx,
    kabsch_align,
    mean_similarity_to_actives_mlx,
    rdkit_grid_shape_tanimoto_matrix_mlx,
    rdkit_shape_occupancy_mlx,
    rdkit_shape_tanimoto_from_mols,
    rdkit_shape_tanimoto_matrix_from_mols,
    shape_carbo_matrix_mlx,
    shape_tanimoto_matrix_mlx,
)
from opencheese.embedding import (
    CheeseEmbeddingBatch,
    CheeseEmbeddingConfig,
    CheeseEmbeddingLoss,
    CheeseEmbeddingOutput,
    CheeseGraphTransformer,
    atom_reconstruction_loss_mlx,
    cheese_autoencoder_loss_mlx,
    cheese_embedding_batch,
    cheese_embedding_batch_from_rdkit_mols,
    cheese_embedding_loss_mlx,
    cheese_embedding_metric_loss,
    embedding_cosine_similarity_matrix_mlx,
    embedding_euclidean_distance_matrix_mlx,
    l2_normalize_mlx,
    local_chiral_volume_features_np,
    masked_mean_mlx,
    pair_distance_reconstruction_loss_mlx,
)

__all__ = [
    "CheeseAlignmentConfig",
    "CheeseAlignmentResult",
    "CheeseBatch",
    "CheeseSimilarityResult",
    "align_cheese_pair",
    "atom_gaussian_parameters_mlx",
    "cheese_alignment_matrix",
    "cheese_batch",
    "cheese_batch_from_rdkit_mols",
    "cheese_similarity_matrix_mlx",
    "cheese_similarity_pairs_mlx",
    "electrostatic_carbo_matrix_mlx",
    "electrostatic_overlap_matrix_mlx",
    "electrostatic_paired_overlap_mlx",
    "electrostatic_potential_on_grid_metal",
    "electrostatic_potential_on_grid_mlx",
    "electrostatic_self_overlap_mlx",
    "electrostatic_similarity_matrix_mlx",
    "electrostatic_similarity_to_template_grids_mlx",
    "electrostatic_similarity_to_template_grids_tiled_mlx",
    "gaussian_shape_overlap_matrix_mlx",
    "gaussian_shape_paired_overlap_mlx",
    "gaussian_shape_self_overlap_mlx",
    "horn_align_pairwise_mlx",
    "kabsch_align",
    "mean_similarity_to_actives_mlx",
    "rdkit_grid_shape_tanimoto_matrix_mlx",
    "rdkit_shape_occupancy_mlx",
    "rdkit_shape_tanimoto_from_mols",
    "rdkit_shape_tanimoto_matrix_from_mols",
    "shape_carbo_matrix_mlx",
    "shape_tanimoto_matrix_mlx",
    "CheeseEmbeddingBatch",
    "CheeseEmbeddingConfig",
    "CheeseEmbeddingLoss",
    "CheeseEmbeddingOutput",
    "CheeseGraphTransformer",
    "atom_reconstruction_loss_mlx",
    "cheese_autoencoder_loss_mlx",
    "cheese_embedding_batch",
    "cheese_embedding_batch_from_rdkit_mols",
    "cheese_embedding_loss_mlx",
    "cheese_embedding_metric_loss",
    "embedding_cosine_similarity_matrix_mlx",
    "embedding_euclidean_distance_matrix_mlx",
    "l2_normalize_mlx",
    "local_chiral_volume_features_np",
    "masked_mean_mlx",
    "pair_distance_reconstruction_loss_mlx",
]
