"""openCHEESE descriptor API.

The implementation is currently provided by the MLX backend in
``mlxmolkit.cheese``. This module is intentionally a public extraction layer:
depend on ``opencheese.descriptors`` in new code, not on the backend module.
"""

from mlxmolkit.cheese import (
    CheeseAlignmentConfig,
    CheeseAlignmentResult,
    CheeseBatch,
    CheeseSimilarityResult,
    align_cheese_pair,
    atom_gaussian_parameters_mlx,
    cheese_alignment_matrix,
    cheese_batch,
    cheese_batch_from_rdkit_mols,
    cheese_similarity_matrix_mlx,
    cheese_similarity_pairs_mlx,
    electrostatic_carbo_matrix_mlx,
    electrostatic_overlap_matrix_mlx,
    electrostatic_paired_overlap_mlx,
    electrostatic_potential_on_grid_metal,
    electrostatic_potential_on_grid_mlx,
    electrostatic_self_overlap_mlx,
    electrostatic_similarity_matrix_mlx,
    electrostatic_similarity_to_template_grids_mlx,
    electrostatic_similarity_to_template_grids_tiled_mlx,
    gaussian_shape_overlap_matrix_mlx,
    gaussian_shape_paired_overlap_mlx,
    gaussian_shape_self_overlap_mlx,
    horn_align_pairwise_mlx,
    kabsch_align,
    mean_similarity_to_actives_mlx,
    rdkit_grid_shape_tanimoto_matrix_mlx,
    rdkit_shape_occupancy_mlx,
    rdkit_shape_tanimoto_from_mols,
    rdkit_shape_tanimoto_matrix_from_mols,
    shape_carbo_matrix_mlx,
    shape_tanimoto_matrix_mlx,
)

__all__ = [
    "CheeseAlignmentConfig",
    "CheeseAlignmentResult",
    "CheeseBatch",
    "CheeseSimilarityResult",
    "align_cheese_pair",
    "atom_gaussian_parameters_mlx",
    "cheese_alignment_matrix",
    "cheese_batch",
    "cheese_batch_from_rdkit_mols",
    "cheese_similarity_matrix_mlx",
    "cheese_similarity_pairs_mlx",
    "electrostatic_carbo_matrix_mlx",
    "electrostatic_overlap_matrix_mlx",
    "electrostatic_paired_overlap_mlx",
    "electrostatic_potential_on_grid_metal",
    "electrostatic_potential_on_grid_mlx",
    "electrostatic_self_overlap_mlx",
    "electrostatic_similarity_matrix_mlx",
    "electrostatic_similarity_to_template_grids_mlx",
    "electrostatic_similarity_to_template_grids_tiled_mlx",
    "gaussian_shape_overlap_matrix_mlx",
    "gaussian_shape_paired_overlap_mlx",
    "gaussian_shape_self_overlap_mlx",
    "horn_align_pairwise_mlx",
    "kabsch_align",
    "mean_similarity_to_actives_mlx",
    "rdkit_grid_shape_tanimoto_matrix_mlx",
    "rdkit_shape_occupancy_mlx",
    "rdkit_shape_tanimoto_from_mols",
    "rdkit_shape_tanimoto_matrix_from_mols",
    "shape_carbo_matrix_mlx",
    "shape_tanimoto_matrix_mlx",
]
