"""One-shot generator for tests/test_mopac_parity.py reference data.

Emits, for each molecule: frozen geometry (RDKit ETKDGv3 seed=1 + MMFF, baked as literals),
MOPAC v23 `PM6 1SCF` heat of formation and NET ATOMIC CHARGES.

Values come from MOPAC's diskless C API rather than from parsing `.out` text.
Same numbers, but no subprocess, no temporary directory and no regex against a
human-readable report whose column layout is not a stable interface — and 9.7x
faster on these eighteen molecules (280 ms -> 29 ms), which matters when the
set is extended.

The API also returns more precision than the report prints: MOPAC writes the
heat of formation to five decimals and charges to four, so the literals below
are rounded to match what the previous text-scraping version could see.

Run:  PYTHONPATH=. python tools/gen_mopac_ref.py > /tmp/mopac_ref_block.py
"""
import numpy as np
from rdkit import Chem, RDLogger
from rdkit.Chem import AllChem

from tools.mopac_api import scf

RDLogger.DisableLog("rdApp.*")
MOLS = [
    ("ethanol", "CCO"),
    ("methanol", "CO"),
    ("acetone", "CC(C)=O"),
    ("dimethyl_sulfide", "CSC"),
    ("methanethiol", "CS"),
    ("dimethyl_disulfide", "CSSC"),
    ("thiophene", "c1ccsc1"),
    ("chlorobenzene", "c1ccccc1Cl"),
    ("trimethyl_phosphate", "COP(=O)(OC)OC"),
    ("hydrogen_chloride", "Cl"),
    ("methyl_chloride", "CCl"),
    ("hydrogen_bromide", "Br"),
    ("methyl_bromide", "CBr"),
    ("ethyl_bromide", "CCBr"),
    ("methyl_iodide", "CI"),
    # multi-iodine: the n=5 two-center overlap regression (was -13937 / -21482 kcal)
    ("diiodomethane", "ICI"),
    ("diiodine", "II"),
    ("trifluoroiodomethane", "FC(F)(F)I"),
]


def main():
    print("# Generated by tools/gen_mopac_ref.py — MOPAC v23.2.5, PM6 1SCF,")
    print("# geometry: RDKit ETKDGv3 randomSeed=1 + MMFF94 (frozen below; do NOT regenerate).")
    print("MOPAC_REF = {")
    for name, smi in MOLS:
        m = Chem.AddHs(Chem.MolFromSmiles(smi))
        AllChem.EmbedMolecule(m, randomSeed=1)
        AllChem.MMFFOptimizeMolecule(m)
        conf = m.GetConformer()
        Z = [a.GetAtomicNum() for a in m.GetAtoms()]
        xyz = np.array([list(conf.GetAtomPosition(i)) for i in range(m.GetNumAtoms())])

        result = scf(Z, xyz, model="PM6")
        hf = round(float(result["heat_kcal"]), 5)
        q = [round(float(v), 4) for v in result["charges"]]

        coords = ", ".join(f"({x:.6f}, {y:.6f}, {z:.6f})" for x, y, z in xyz)
        print(f'    "{name}": dict(')
        print(f'        smiles="{smi}",')
        print(f"        atoms={Z},")
        print(f"        coords=[{coords}],")
        print(f"        hf_kcal={hf},")
        print(f"        charges={q},")
        print("    ),")
    print("}")


if __name__ == "__main__":
    main()
