"""Regenerate tests/_d3bj_ref_generated.py from Grimme's simple-dftd3.

The reference lives in a separate environment on purpose: simple-dftd3 is not
a runtime dependency of mlxmolkit, it is only the thing we validate against.

    python -m venv /tmp/d3venv
    /tmp/d3venv/bin/pip install numpy dftd3
    /tmp/d3venv/bin/python tools/gen_d3bj_ref.py

Geometries are frozen in the generated file, so the test does not depend on
RDKit's embedding staying bit-identical across versions.
"""
from __future__ import annotations

import numpy as np

BOHR = 0.5291772083

# wB97M-D3BJ, the parameters PM6-ML uses unmodified.
PARAMS = dict(s6=1.0, s8=0.3908, a1=0.566, a2=3.128)

# (name, atomic numbers, coordinates in Angstrom) — kept here rather than
# regenerated from SMILES so the reference is reproducible without RDKit.
try:
    from tests._d3bj_ref_generated import D3BJ_REF as _EXISTING
except Exception:  # pragma: no cover - first run
    _EXISTING = {}


def main() -> None:
    from dftd3.interface import DispersionModel, RationalDampingParam

    if not _EXISTING:
        raise SystemExit(
            "No existing fixture to take geometries from. Seed it first with "
            "the SMILES list used in tests/test_d3bj_and_halogen.py."
        )

    rows = []
    for name, case in _EXISTING.items():
        Z = np.array(case["atoms"])
        xyz_ang = np.array(case["coords"], dtype=float)
        model = DispersionModel(Z, xyz_ang / BOHR)
        # s9=0 -> two-body only. PM6-ML additionally switches on the
        # three-body ATM term; mlxmolkit's d3bj_energy is two-body, so the
        # reference must match that to be a like-for-like check.
        param = RationalDampingParam(s9=0.0, **PARAMS)
        energy = float(np.asarray(
            model.get_dispersion(param, grad=False)["energy"]).reshape(-1)[0])
        rows.append((name, case["atoms"], xyz_ang.tolist(), energy))

    out = ['"""D3(BJ) reference energies from Grimme\'s simple-dftd3.',
           "",
           "Generated by tools/gen_d3bj_ref.py — do NOT hand-edit.",
           "Reference: simple-dftd3 (dftd3 python bindings), s9=0 (two-body only),",
           "wB97M-D3BJ parameters s6=1.0, s8=0.3908, a1=0.566, a2=3.128.",
           "Geometries: RDKit ETKDG seed=42, frozen below.",
           "Energies in Hartree.",
           '"""', "", "D3BJ_REF = {"]
    for name, atoms, coords, energy in rows:
        out.append(f"    {name!r}: dict(")
        out.append(f"        atoms={atoms},")
        out.append(f"        coords={[[round(v, 6) for v in r] for r in coords]},")
        out.append(f"        energy_hartree={energy!r},")
        out.append("    ),")
    out.append("}")

    with open("tests/_d3bj_ref_generated.py", "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {len(rows)} reference entries")


if __name__ == "__main__":
    main()
