"""One-shot generator for tests/test_mopac_parity.py reference data.

Emits, for each molecule: frozen geometry (RDKit ETKDGv3 seed=1 + MMFF, baked as literals),
MOPAC v23 `PM6 1SCF` heat of formation and NET ATOMIC CHARGES.

Run:  PYTHONPATH=. python tools/gen_mopac_ref.py > /tmp/mopac_ref_block.py
"""
import re
import subprocess
import tempfile
from pathlib import Path

import numpy as np
from rdkit import Chem, RDLogger
from rdkit.Chem import AllChem

RDLogger.DisableLog("rdApp.*")
MOPAC = "/Users/guillaume-osmo/miniconda3/envs/osmo/bin/mopac"

MOLS = [
    ("ethanol", "CCO"),
    ("methanol", "CO"),
    ("acetone", "CC(C)=O"),
    ("dimethyl_sulfide", "CSC"),
    ("methanethiol", "CS"),
    ("dimethyl_disulfide", "CSSC"),
    ("thiophene", "c1ccsc1"),
    ("chlorobenzene", "c1ccccc1Cl"),
    ("trimethyl_phosphate", "COP(=O)(OC)OC"),
    ("hydrogen_chloride", "Cl"),
    ("methyl_chloride", "CCl"),
    ("hydrogen_bromide", "Br"),
    ("methyl_bromide", "CBr"),
    ("ethyl_bromide", "CCBr"),
    ("methyl_iodide", "CI"),
    # multi-iodine: the n=5 two-center overlap regression (was -13937 / -21482 kcal)
    ("diiodomethane", "ICI"),
    ("diiodine", "II"),
    ("trifluoroiodomethane", "FC(F)(F)I"),
]


def main():
    print("# Generated by tools/gen_mopac_ref.py — MOPAC v23.2.5, PM6 1SCF,")
    print("# geometry: RDKit ETKDGv3 randomSeed=1 + MMFF94 (frozen below; do NOT regenerate).")
    print("MOPAC_REF = {")
    with tempfile.TemporaryDirectory() as td:
        for name, smi in MOLS:
            m = Chem.AddHs(Chem.MolFromSmiles(smi))
            AllChem.EmbedMolecule(m, randomSeed=1)
            AllChem.MMFFOptimizeMolecule(m)
            conf = m.GetConformer()
            Z = [a.GetAtomicNum() for a in m.GetAtoms()]
            sym = [a.GetSymbol() for a in m.GetAtoms()]
            xyz = np.array([list(conf.GetAtomPosition(i)) for i in range(m.GetNumAtoms())])

            mop = Path(td) / f"{name}.mop"
            lines = ["PM6 1SCF", name, ""]
            lines += [f"{s:2s} {x:.6f} 1 {y:.6f} 1 {z:.6f} 1" for s, (x, y, z) in zip(sym, xyz)]
            mop.write_text("\n".join(lines) + "\n")
            subprocess.run([MOPAC, mop.name], cwd=td, capture_output=True, timeout=120)
            out = (Path(td) / f"{name}.out").read_text()
            hf = float(re.search(r"FINAL HEAT OF FORMATION\s*=\s*(-?\d+\.\d+)\s*KCAL", out).group(1))
            qm = re.search(r"NET ATOMIC CHARGES.*?\n(.*?)\n\s*DIPOLE", out, re.S)
            q = [float(ln.split()[2]) for ln in qm.group(1).splitlines()
                 if len(ln.split()) >= 3 and ln.split()[0].isdigit()]

            coords = ", ".join(f"({x:.6f}, {y:.6f}, {z:.6f})" for x, y, z in xyz)
            print(f'    "{name}": dict(')
            print(f'        smiles="{smi}",')
            print(f"        atoms={Z},")
            print(f"        coords=[{coords}],")
            print(f"        hf_kcal={hf},")
            print(f"        charges={[round(v, 4) for v in q]},")
            print("    ),")
    print("}")


if __name__ == "__main__":
    main()
